import React, { useEffect, useMemo, useState } from "react";
import logoLongitude from "../assets/logo-longitude.png";
import { deleteRow, getSettings, insertRow, listRows, onlineConfigured, onlineSession, saveSettings, updateRow } from "../core/opsApi";

const emptyClient={name:"",document:"",phone:"",email:"",address:"",notes:""};
const emptyProperty={client_id:"",name:"",municipality:"",state:"MT",registration:"",car_code:"",sigef_code:"",area_ha:"",status:"Em andamento",notes:""};
const emptyReport={client_id:"",property_id:"",title:"",report_type:"Relatório técnico",status:"Rascunho",reference_date:new Date().toISOString().slice(0,10),summary:""};
const emptyProposal={client_id:"",property_id:"",service:"",amount:"",deadline:"",payment_terms:"",scope:"",status:"Em elaboração",validity_date:""};
const emptyAnalysis={client_id:"",property_id:"",analysis_type:"Consulta territorial",reference_date:new Date().toISOString().slice(0,10),area_ha:"",occurrences:"",status:"Preliminar",notes:""};
const defaultSettings={company_name:"Longitude Assessoria Rural e Cartorial",trade_name:"Longitude Geo Intelligence",phone:"(65) 99670-1319",email:"longitudecba@gmail.com",address:"Cuiabá/MT",technical_responsible:"Alexandre Magno Gomes de Lima",document:"",report_footer:"Uso técnico preliminar. Conferir os dados e documentos oficiais."};
const tableMap={client:"lg_clients",property:"lg_properties",report:"lg_reports",proposal:"lg_proposals",analysis:"lg_analyses"};
function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function dateBR(v){if(!v)return"-";const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("pt-BR")}
function safe(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function downloadJson(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function printDocument(title,html,settings){const w=window.open("","_blank","width=1200,height=880");if(!w)return alert("Libere pop-ups para gerar o documento.");w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${safe(title)}</title><style>@page{size:A4;margin:14mm}body{font-family:Arial;color:#17221c}header{display:flex;gap:16px;align-items:center;border-bottom:3px solid #0f766e;padding-bottom:12px}header img{width:82px;height:82px;object-fit:contain}h1{color:#075985;margin:0}h2{color:#166534}.meta{background:#f1f5f9;border-left:5px solid #10b981;padding:12px;margin:16px 0}.actions{margin-bottom:14px}@media print{.actions{display:none}}</style></head><body><div class="actions"><button onclick="window.print()">Imprimir / Salvar PDF</button></div><header><img src="${logoLongitude}"><div><h1>${safe(settings.trade_name||settings.company_name)}</h1><div>${safe(settings.company_name)}</div></div></header>${html}<p style="margin-top:28px;border-top:1px solid #94a3b8;padding-top:10px">${safe(settings.report_footer||"")}</p></body></html>`);w.document.close()}

export default function EnterpriseModules({module}){
 const [data,setData]=useState({clients:[],properties:[],reports:[],proposals:[],analyses:[]});
 const [settings,setSettings]=useState(defaultSettings);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [search,setSearch]=useState("");
 const [client,setClient]=useState(emptyClient),[property,setProperty]=useState(emptyProperty),[report,setReport]=useState(emptyReport),[proposal,setProposal]=useState(emptyProposal),[analysis,setAnalysis]=useState(emptyAnalysis);
 const [editing,setEditing]=useState({type:"",id:""});const [selectedProperty,setSelectedProperty]=useState(null);const [diagnostic,setDiagnostic]=useState([]);
 const configured=onlineConfigured(),session=onlineSession();
 async function reload(){setLoading(true);setMessage("");try{if(!configured)throw new Error("Supabase não configurado.");if(!onlineSession())throw new Error("Faça login primeiro em Cloud / Consulta Territorial.");const [clients,properties,reports,proposals,analyses,remoteSettings]=await Promise.all([listRows("lg_clients"),listRows("lg_properties"),listRows("lg_reports"),listRows("lg_proposals"),listRows("lg_analyses"),getSettings()]);setData({clients,properties,reports,proposals,analyses});if(remoteSettings)setSettings({...defaultSettings,...remoteSettings});}catch(e){setMessage(e.message)}finally{setLoading(false)}}
 useEffect(()=>{reload()},[]);
 const clientName=id=>data.clients.find(x=>x.id===id)?.name||"-",propertyName=id=>data.properties.find(x=>x.id===id)?.name||"-";
 const filtered=(rows,fields)=>rows.filter(r=>fields.some(f=>String(r[f]||"").toLowerCase().includes(search.toLowerCase())));
 const stats=useMemo(()=>({clients:data.clients.length,properties:data.properties.length,reports:data.reports.length,proposals:data.proposals.length,analyses:data.analyses.length,pipeline:data.proposals.reduce((s,p)=>s+Number(p.amount||0),0)}),[data]);
 async function save(type,form,reset){try{setMessage("");const payload={...form};if(type==="property"||type==="analysis")payload.area_ha=payload.area_ha?Number(String(payload.area_ha).replace(",",".")):null;if(type==="analysis")payload.occurrences=payload.occurrences?Number(payload.occurrences):0;if(type==="proposal")payload.amount=payload.amount?Number(String(payload.amount).replace(/\./g,"").replace(",",".")):null;if(editing.type===type&&editing.id)await updateRow(tableMap[type],editing.id,payload);else await insertRow(tableMap[type],payload);setEditing({type:"",id:""});reset();await reload();setMessage("Registro salvo na nuvem.")}catch(e){setMessage(`Não foi possível salvar: ${e.message}`)}}
 async function remove(table,id){if(!confirm("Excluir este registro?"))return;try{await deleteRow(table,id);await reload()}catch(e){setMessage(e.message)}}
 function edit(type,row,setter){setEditing({type,id:row.id});const c={...row};["id","owner_id","created_at","updated_at"].forEach(k=>delete c[k]);setter(c);window.scrollTo({top:0,behavior:"smooth"})}
 async function runDiagnostic(){const tests=[];tests.push({name:"Configuração Supabase",ok:configured});tests.push({name:"Sessão autenticada",ok:Boolean(onlineSession()?.access_token)});for(const [label,table] of [["Clientes","lg_clients"],["Imóveis","lg_properties"],["Análises","lg_analyses"],["Relatórios","lg_reports"],["Propostas","lg_proposals"]]){try{await listRows(table);tests.push({name:`Tabela ${label}`,ok:true})}catch(e){tests.push({name:`Tabela ${label}`,ok:false,detail:e.message})}}setDiagnostic(tests)}
 if(!configured||!session)return <section className="enterprise-page"><div className="enterprise-alert"><h3>Módulos online aguardando autenticação</h3><p>{message||"Entre em Cloud / Consulta Territorial e retorne a este menu."}</p><button className="primary-button" onClick={reload}>Verificar novamente</button></div></section>;
 if(loading)return <section className="enterprise-page"><div className="enterprise-alert"><h3>Sincronizando com a nuvem...</h3></div></section>;
 const history=selectedProperty?{reports:data.reports.filter(x=>x.property_id===selectedProperty.id),proposals:data.proposals.filter(x=>x.property_id===selectedProperty.id),analyses:data.analyses.filter(x=>x.property_id===selectedProperty.id)}:null;
 if(module==="dashboard")return <Page><Header title="Dashboard" onReload={reload}/>{message&&<Message>{message}</Message>}<div className="enterprise-metrics"><Metric label="Clientes" value={stats.clients}/><Metric label="Imóveis" value={stats.properties}/><Metric label="Análises" value={stats.analyses}/><Metric label="Relatórios" value={stats.reports}/><Metric label="Propostas" value={stats.proposals}/><Metric label="Carteira" value={money(stats.pipeline)}/></div><div className="enterprise-columns"><Panel title="Imóveis recentes">{data.properties.slice(0,7).map(p=><Row key={p.id} title={p.name} subtitle={`${p.municipality||"-"}/${p.state||"-"} • ${p.status||"-"}`}/>)}</Panel><Panel title="Atividade recente">{[...data.analyses.map(x=>({date:x.created_at,title:x.analysis_type,sub:`Análise • ${propertyName(x.property_id)}`})),...data.reports.map(x=>({date:x.created_at,title:x.title,sub:`Relatório • ${propertyName(x.property_id)}`})),...data.proposals.map(x=>({date:x.created_at,title:x.service,sub:`Proposta • ${money(x.amount)}`}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8).map((x,i)=><Row key={i} title={x.title} subtitle={x.sub}/>)}</Panel></div></Page>;
 if(module==="clientes")return <Page><Header title="Clientes" onReload={reload}/>{message&&<Message>{message}</Message>}<div className="enterprise-columns"><ClientForm value={client} setValue={setClient} editing={editing.type==="client"} onSubmit={()=>save("client",client,()=>setClient(emptyClient))}/><Panel title="Clientes cadastrados" search={search} setSearch={setSearch}>{filtered(data.clients,["name","document","phone","email"]).map(r=><CrudRow key={r.id} title={r.name} subtitle={`${r.document||"Sem CPF/CNPJ"} • ${r.phone||"Sem telefone"}`} onEdit={()=>edit("client",r,setClient)} onDelete={()=>remove("lg_clients",r.id)}/>)}</Panel></div></Page>;
 if(module==="imoveis")return <Page><Header title="Imóveis e histórico" onReload={reload}/>{message&&<Message>{message}</Message>}<div className="enterprise-columns"><PropertyForm value={property} setValue={setProperty} clients={data.clients} editing={editing.type==="property"} onSubmit={()=>save("property",property,()=>setProperty(emptyProperty))}/><Panel title="Imóveis cadastrados" search={search} setSearch={setSearch}>{filtered(data.properties,["name","municipality","registration","car_code","sigef_code"]).map(r=><CrudRow key={r.id} title={r.name} subtitle={`${r.municipality||"-"}/${r.state||"-"} • ${clientName(r.client_id)} • ${r.area_ha||0} ha`} extra={<button onClick={()=>{setSelectedProperty(r);setAnalysis({...emptyAnalysis,property_id:r.id,client_id:r.client_id||""})}}>Histórico</button>} onEdit={()=>edit("property",r,setProperty)} onDelete={()=>remove("lg_properties",r.id)}/>)}</Panel></div>{selectedProperty&&<PropertyHistory property={selectedProperty} history={history} analysis={analysis} setAnalysis={setAnalysis} onSave={()=>save("analysis",analysis,()=>setAnalysis({...emptyAnalysis,property_id:selectedProperty.id,client_id:selectedProperty.client_id||""}))} onClose={()=>setSelectedProperty(null)} onDeleteAnalysis={id=>remove("lg_analyses",id)}/>}</Page>;
 if(module==="relatorios")return <Page><Header title="Relatórios" onReload={reload}/>{message&&<Message>{message}</Message>}<div className="enterprise-columns"><ReportForm value={report} setValue={setReport} data={data} onSubmit={()=>save("report",report,()=>setReport(emptyReport))}/><Panel title="Arquivo de relatórios" search={search} setSearch={setSearch}>{filtered(data.reports,["title","report_type","status","summary"]).map(r=><CrudRow key={r.id} title={r.title} subtitle={`${r.report_type} • ${propertyName(r.property_id)} • ${r.status}`} extra={<button onClick={()=>printDocument(r.title,`<div class="meta"><b>Tipo:</b> ${safe(r.report_type)}<br><b>Cliente:</b> ${safe(clientName(r.client_id))}<br><b>Imóvel:</b> ${safe(propertyName(r.property_id))}<br><b>Referência:</b> ${safe(dateBR(r.reference_date))}<br><b>Status:</b> ${safe(r.status)}</div><h2>Resumo</h2><p>${safe(r.summary||"Sem resumo.")}</p>`,settings)}>PDF</button>} onEdit={()=>edit("report",r,setReport)} onDelete={()=>remove("lg_reports",r.id)}/>)}</Panel></div></Page>;
 if(module==="propostas")return <Page><Header title="Propostas" onReload={reload}/>{message&&<Message>{message}</Message>}<div className="enterprise-columns"><ProposalForm value={proposal} setValue={setProposal} data={data} onSubmit={()=>save("proposal",proposal,()=>setProposal(emptyProposal))}/><Panel title="Propostas cadastradas" search={search} setSearch={setSearch}>{filtered(data.proposals,["service","status","scope"]).map(p=><CrudRow key={p.id} title={p.service} subtitle={`${clientName(p.client_id)} • ${money(p.amount)} • ${p.status}`} extra={<button onClick={()=>printDocument(`Proposta — ${p.service}`,`<div class="meta"><b>Cliente:</b> ${safe(clientName(p.client_id))}<br><b>Imóvel:</b> ${safe(propertyName(p.property_id))}<br><b>Serviço:</b> ${safe(p.service)}<br><b>Valor:</b> ${safe(money(p.amount))}<br><b>Prazo:</b> ${safe(p.deadline||"A definir")}<br><b>Validade:</b> ${safe(dateBR(p.validity_date))}</div><h2>Escopo</h2><p>${safe(p.scope||"Não informado.")}</p><h2>Pagamento</h2><p>${safe(p.payment_terms||"A combinar.")}</p>`,settings)}>PDF</button>} onEdit={()=>edit("proposal",p,setProposal)} onDelete={()=>remove("lg_proposals",p.id)}/>)}</Panel></div></Page>;
 if(module==="config")return <Page><Header title="Configurações e diagnóstico" onReload={reload}/>{message&&<Message>{message}</Message>}<div className="enterprise-columns"><SettingsForm value={settings} setValue={setSettings} onSubmit={async()=>{try{await saveSettings(settings);setMessage("Configurações salvas na nuvem.")}catch(e){setMessage(e.message)}}}/><div><Panel title="Diagnóstico para publicação"><button className="primary-button enterprise-full-button" onClick={runDiagnostic}>Executar diagnóstico</button>{diagnostic.map((x,i)=><div key={i} className={`enterprise-health ${x.ok?"ok":"fail"}`}><strong>{x.ok?"✓":"✕"} {x.name}</strong>{x.detail&&<span>{x.detail}</span>}</div>)}</Panel><Panel title="Backup"><button className="secondary-action enterprise-full-button" onClick={()=>downloadJson(`longitude_geo_backup_${new Date().toISOString().slice(0,10)}.json`,{exported_at:new Date().toISOString(),settings,data})}>Baixar backup JSON</button><Row title={session.user?.email||"Usuário"} subtitle="Sessão atual autenticada"/></Panel></div></div></Page>;
 return null;
}
const Page=({children})=><section className="enterprise-page">{children}</section>;
const Message=({children})=><p className="enterprise-message">{children}</p>;
function Header({title,onReload}){return <div className="enterprise-toolbar"><div><h3>{title}</h3><p>Gestão integrada e sincronizada no Supabase.</p></div><button className="secondary-action" onClick={onReload}>Atualizar</button></div>}
function Metric({label,value}){return <div className="enterprise-metric"><span>{label}</span><strong>{value}</strong></div>}
function Panel({title,children,search,setSearch}){return <div className="enterprise-panel"><div className="enterprise-panel-head"><h3>{title}</h3>{setSearch&&<input placeholder="Pesquisar..." value={search} onChange={e=>setSearch(e.target.value)}/>}</div><div className="enterprise-list">{React.Children.count(children)?children:<p className="muted">Nenhum registro.</p>}</div></div>}
function Row({title,subtitle}){return <div className="enterprise-row"><div><strong>{title}</strong><span>{subtitle}</span></div></div>}
function CrudRow({title,subtitle,onEdit,onDelete,extra}){return <div className="enterprise-row"><div><strong>{title}</strong><span>{subtitle}</span></div><div className="enterprise-row-actions">{extra}<button onClick={onEdit}>Editar</button><button className="danger-mini" onClick={onDelete}>Excluir</button></div></div>}
function Form({title,onSubmit,children,button="Salvar na nuvem"}){return <form className="enterprise-form" onSubmit={e=>{e.preventDefault();onSubmit()}}><h3>{title}</h3>{children}<button className="primary-button">{button}</button></form>}
function ClientForm({value,setValue,editing,onSubmit}){return <Form title={editing?"Editar cliente":"Novo cliente"} onSubmit={onSubmit}><input required placeholder="Nome / Razão social" value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/><input placeholder="CPF/CNPJ" value={value.document} onChange={e=>setValue({...value,document:e.target.value})}/><input placeholder="Telefone" value={value.phone} onChange={e=>setValue({...value,phone:e.target.value})}/><input type="email" placeholder="E-mail" value={value.email} onChange={e=>setValue({...value,email:e.target.value})}/><input placeholder="Endereço" value={value.address} onChange={e=>setValue({...value,address:e.target.value})}/><textarea placeholder="Observações" value={value.notes} onChange={e=>setValue({...value,notes:e.target.value})}/></Form>}
function PropertyForm({value,setValue,clients,editing,onSubmit}){return <Form title={editing?"Editar imóvel":"Novo imóvel"} onSubmit={onSubmit}><select value={value.client_id||""} onChange={e=>setValue({...value,client_id:e.target.value||null})}><option value="">Selecione o cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input required placeholder="Nome do imóvel" value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/><input placeholder="Município" value={value.municipality} onChange={e=>setValue({...value,municipality:e.target.value})}/><input maxLength="2" placeholder="UF" value={value.state} onChange={e=>setValue({...value,state:e.target.value.toUpperCase()})}/><input placeholder="Matrícula" value={value.registration} onChange={e=>setValue({...value,registration:e.target.value})}/><input placeholder="Código CAR" value={value.car_code} onChange={e=>setValue({...value,car_code:e.target.value})}/><input placeholder="Código SIGEF" value={value.sigef_code} onChange={e=>setValue({...value,sigef_code:e.target.value})}/><input placeholder="Área ha" value={value.area_ha} onChange={e=>setValue({...value,area_ha:e.target.value})}/><select value={value.status} onChange={e=>setValue({...value,status:e.target.value})}><option>Em andamento</option><option>Aguardando documentos</option><option>Em análise</option><option>Concluído</option><option>Suspenso</option></select><textarea placeholder="Observações" value={value.notes} onChange={e=>setValue({...value,notes:e.target.value})}/></Form>}
function ReportForm({value,setValue,data,onSubmit}){return <Form title="Registrar relatório" onSubmit={onSubmit}><input required placeholder="Título" value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/><select value={value.report_type} onChange={e=>setValue({...value,report_type:e.target.value})}><option>Relatório técnico</option><option>Relatório de sobreposição</option><option>Parecer técnico</option><option>Laudo de posse</option><option>Relatório registral</option></select><select value={value.client_id||""} onChange={e=>setValue({...value,client_id:e.target.value||null})}><option value="">Sem cliente</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={value.property_id||""} onChange={e=>setValue({...value,property_id:e.target.value||null})}><option value="">Sem imóvel</option>{data.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="date" value={value.reference_date||""} onChange={e=>setValue({...value,reference_date:e.target.value})}/><select value={value.status} onChange={e=>setValue({...value,status:e.target.value})}><option>Rascunho</option><option>Em revisão</option><option>Finalizado</option><option>Entregue</option></select><textarea required placeholder="Resumo técnico" value={value.summary} onChange={e=>setValue({...value,summary:e.target.value})}/></Form>}
function ProposalForm({value,setValue,data,onSubmit}){return <Form title="Nova proposta" onSubmit={onSubmit}><select value={value.client_id||""} onChange={e=>setValue({...value,client_id:e.target.value||null})}><option value="">Selecione o cliente</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={value.property_id||""} onChange={e=>setValue({...value,property_id:e.target.value||null})}><option value="">Selecione o imóvel</option>{data.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input required placeholder="Serviço" value={value.service} onChange={e=>setValue({...value,service:e.target.value})}/><input required placeholder="Valor em R$" value={value.amount} onChange={e=>setValue({...value,amount:e.target.value})}/><input placeholder="Prazo" value={value.deadline} onChange={e=>setValue({...value,deadline:e.target.value})}/><input type="date" value={value.validity_date||""} onChange={e=>setValue({...value,validity_date:e.target.value})}/><textarea placeholder="Escopo" value={value.scope} onChange={e=>setValue({...value,scope:e.target.value})}/><textarea placeholder="Pagamento" value={value.payment_terms} onChange={e=>setValue({...value,payment_terms:e.target.value})}/><select value={value.status} onChange={e=>setValue({...value,status:e.target.value})}><option>Em elaboração</option><option>Enviada</option><option>Aprovada</option><option>Recusada</option><option>Concluída</option></select></Form>}
function SettingsForm({value,setValue,onSubmit}){return <Form title="Perfil da empresa" onSubmit={onSubmit}><input placeholder="Razão social" value={value.company_name||""} onChange={e=>setValue({...value,company_name:e.target.value})}/><input placeholder="Nome da plataforma" value={value.trade_name||""} onChange={e=>setValue({...value,trade_name:e.target.value})}/><input placeholder="Telefone" value={value.phone||""} onChange={e=>setValue({...value,phone:e.target.value})}/><input placeholder="E-mail" value={value.email||""} onChange={e=>setValue({...value,email:e.target.value})}/><input placeholder="Endereço" value={value.address||""} onChange={e=>setValue({...value,address:e.target.value})}/><input placeholder="Responsável técnico" value={value.technical_responsible||""} onChange={e=>setValue({...value,technical_responsible:e.target.value})}/><input placeholder="CPF/CNPJ ou registro" value={value.document||""} onChange={e=>setValue({...value,document:e.target.value})}/><textarea placeholder="Rodapé dos relatórios" value={value.report_footer||""} onChange={e=>setValue({...value,report_footer:e.target.value})}/></Form>}
function PropertyHistory({property,history,analysis,setAnalysis,onSave,onClose,onDeleteAnalysis}){return <div className="enterprise-history"><div className="enterprise-toolbar"><div><h3>Histórico — {property.name}</h3><p>{property.municipality||"-"}/{property.state||"-"} • Matrícula {property.registration||"não informada"}</p></div><button className="secondary-action" onClick={onClose}>Fechar</button></div><div className="enterprise-columns"><Form title="Registrar análise" onSubmit={onSave}><select value={analysis.analysis_type} onChange={e=>setAnalysis({...analysis,analysis_type:e.target.value})}><option>Consulta territorial</option><option>Sobreposição</option><option>Diagnóstico registral</option><option>Vizinhos e confrontantes</option><option>Auditoria SIGEF</option></select><input type="date" value={analysis.reference_date} onChange={e=>setAnalysis({...analysis,reference_date:e.target.value})}/><input placeholder="Área analisada (ha)" value={analysis.area_ha} onChange={e=>setAnalysis({...analysis,area_ha:e.target.value})}/><input placeholder="Ocorrências encontradas" value={analysis.occurrences} onChange={e=>setAnalysis({...analysis,occurrences:e.target.value})}/><select value={analysis.status} onChange={e=>setAnalysis({...analysis,status:e.target.value})}><option>Preliminar</option><option>Em revisão</option><option>Validada</option><option>Concluída</option></select><textarea placeholder="Conclusão / observações" value={analysis.notes} onChange={e=>setAnalysis({...analysis,notes:e.target.value})}/></Form><Panel title="Linha do tempo">{[...history.analyses.map(x=>({date:x.reference_date||x.created_at,title:x.analysis_type,sub:`${x.status} • ${x.occurrences||0} ocorrência(s)`,id:x.id,type:"analysis"})),...history.reports.map(x=>({date:x.reference_date||x.created_at,title:x.title,sub:`Relatório • ${x.status}`})),...history.proposals.map(x=>({date:x.created_at,title:x.service,sub:`Proposta • ${money(x.amount)} • ${x.status}`}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map((x,i)=><div className="enterprise-row" key={`${x.type||"item"}-${x.id||i}`}><div><strong>{x.title}</strong><span>{dateBR(x.date)} • {x.sub}</span></div>{x.type==="analysis"&&<button className="danger-mini" onClick={()=>onDeleteAnalysis(x.id)}>Excluir</button>}</div>)}</Panel></div></div>}
