import React, { useEffect, useMemo, useState } from "react";
import logoLongitude from "../assets/logo-longitude.png";
import { deleteRow, getSettings, insertRow, listRows, onlineConfigured, onlineSession, saveSettings, updateRow } from "../core/opsApi";

const emptyClient = { name: "", document: "", phone: "", email: "", address: "", notes: "" };
const emptyProperty = { client_id: "", name: "", municipality: "", state: "MT", registration: "", car_code: "", sigef_code: "", area_ha: "", status: "Em andamento", notes: "" };
const emptyReport = { client_id: "", property_id: "", title: "", report_type: "Relatório técnico", status: "Rascunho", reference_date: new Date().toISOString().slice(0,10), summary: "" };
const emptyProposal = { client_id: "", property_id: "", service: "", amount: "", deadline: "", payment_terms: "", scope: "", status: "Em elaboração", validity_date: "" };
const defaultSettings = { company_name: "Longitude Assessoria Rural e Cartorial", trade_name: "Longitude Geo Intelligence", phone: "(65) 99670-1319", email: "longitudecba@gmail.com", address: "Cuiabá/MT", technical_responsible: "Alexandre Magno Gomes de Lima", document: "", report_footer: "Uso técnico preliminar. Conferir os dados e documentos oficiais." };

function money(value) { return Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function dateBR(value) { if (!value) return "-"; const d = new Date(`${String(value).slice(0,10)}T12:00:00`); return Number.isNaN(d.getTime()) ? value : d.toLocaleDateString("pt-BR"); }
function downloadJson(name, data) { const url = URL.createObjectURL(new Blob([JSON.stringify(data,null,2)], {type:"application/json"})); const a=document.createElement("a"); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
function safe(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}

function printDocument(title, html, settings) {
  const w = window.open("", "_blank", "width=1100,height=850");
  if (!w) return alert("Libere pop-ups para gerar o documento.");
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${safe(title)}</title><style>body{font-family:Arial;margin:28px;color:#17221c}header{display:flex;gap:18px;align-items:center;border-bottom:3px solid #0f766e;padding-bottom:14px}header img{width:90px;height:90px;object-fit:contain}h1{color:#075985;margin:0}h2{color:#166534}.meta{background:#f1f5f9;border-left:5px solid #10b981;padding:12px;margin:16px 0}table{width:100%;border-collapse:collapse}th,td{border:1px solid #cbd5e1;padding:8px;text-align:left}th{background:#e2e8f0}.actions{margin-bottom:15px}@media print{.actions{display:none}body{margin:10mm}}</style></head><body><div class="actions"><button onclick="window.print()">Imprimir / Salvar PDF</button></div><header><img src="${logoLongitude}"><div><h1>${safe(settings.trade_name || settings.company_name)}</h1><div>${safe(settings.company_name)}</div></div></header>${html}<p style="margin-top:30px;border-top:1px solid #94a3b8;padding-top:10px">${safe(settings.report_footer || "")}</p></body></html>`); w.document.close();
}

export default function EnterpriseModules({ module }) {
  const [data,setData]=useState({clients:[],properties:[],reports:[],proposals:[]});
  const [settings,setSettings]=useState(defaultSettings);
  const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [search,setSearch]=useState("");
  const [client,setClient]=useState(emptyClient); const [property,setProperty]=useState(emptyProperty); const [report,setReport]=useState(emptyReport); const [proposal,setProposal]=useState(emptyProposal);
  const [editing,setEditing]=useState({type:"",id:""});
  const configured=onlineConfigured(), session=onlineSession();

  async function reload(){ setLoading(true); setMessage(""); try { if(!configured) throw new Error("Supabase não configurado."); if(!session) throw new Error("Faça login primeiro em Cloud / Consulta Territorial."); const [clients,properties,reports,proposals,remoteSettings]=await Promise.all([listRows("lg_clients"),listRows("lg_properties"),listRows("lg_reports"),listRows("lg_proposals"),getSettings()]); setData({clients,properties,reports,proposals}); if(remoteSettings) setSettings({...defaultSettings,...remoteSettings}); } catch(e){setMessage(e.message);} finally{setLoading(false);} }
  useEffect(()=>{reload();},[]);
  const clientName=(id)=>data.clients.find(x=>x.id===id)?.name||"-"; const propertyName=(id)=>data.properties.find(x=>x.id===id)?.name||"-";
  const filtered=(rows,fields)=>rows.filter(r=>fields.some(f=>String(r[f]||"").toLowerCase().includes(search.toLowerCase())));
  const stats=useMemo(()=>({clients:data.clients.length,properties:data.properties.length,reports:data.reports.length,proposals:data.proposals.length,pipeline:data.proposals.reduce((s,p)=>s+Number(p.amount||0),0)}),[data]);

  async function save(type,form,reset){ try{setMessage(""); const table={client:"lg_clients",property:"lg_properties",report:"lg_reports",proposal:"lg_proposals"}[type]; const payload={...form}; if(type==="property") payload.area_ha=payload.area_ha?Number(String(payload.area_ha).replace(",",".")):null; if(type==="proposal") payload.amount=payload.amount?Number(String(payload.amount).replace(/\./g,"").replace(",",".")):null; if(editing.type===type&&editing.id) await updateRow(table,editing.id,payload); else await insertRow(table,payload); setEditing({type:"",id:""}); reset(); await reload(); setMessage("Registro salvo na nuvem."); }catch(e){setMessage(`Não foi possível salvar: ${e.message}`);} }
  async function remove(table,id){if(!confirm("Excluir este registro?"))return; try{await deleteRow(table,id); await reload();}catch(e){setMessage(e.message);}}
  function edit(type,row,setter){setEditing({type,id:row.id}); const copy={...row}; delete copy.id; delete copy.owner_id; delete copy.created_at; delete copy.updated_at; setter(copy); window.scrollTo({top:0,behavior:"smooth"});}

  if(!configured||!session) return <section className="enterprise-page"><div className="enterprise-alert"><h3>Módulos online aguardando autenticação</h3><p>{message||"Entre em Cloud / Consulta Territorial e depois retorne a este menu."}</p><button className="primary-button" onClick={reload}>Verificar novamente</button></div></section>;
  if(loading) return <section className="enterprise-page"><div className="enterprise-alert"><h3>Sincronizando com a nuvem...</h3></div></section>;

  if(module==="dashboard") return <section className="enterprise-page"><div className="enterprise-toolbar"><div><h3>Visão geral operacional</h3><p>Dados centralizados no Supabase, disponíveis em qualquer dispositivo autorizado.</p></div><button className="secondary-action" onClick={reload}>Atualizar</button></div>{message&&<p className="enterprise-message">{message}</p>}<div className="enterprise-metrics"><Metric label="Clientes" value={stats.clients}/><Metric label="Imóveis" value={stats.properties}/><Metric label="Relatórios" value={stats.reports}/><Metric label="Propostas" value={stats.proposals}/><Metric label="Carteira de propostas" value={money(stats.pipeline)}/></div><div className="enterprise-columns"><Panel title="Últimos imóveis">{data.properties.slice(0,6).map(p=><Row key={p.id} title={p.name} subtitle={`${p.municipality||"Município não informado"}/${p.state||"-"} • ${p.status||"-"}`}/>)}</Panel><Panel title="Últimas propostas">{data.proposals.slice(0,6).map(p=><Row key={p.id} title={p.service} subtitle={`${clientName(p.client_id)} • ${money(p.amount)} • ${p.status}`}/>)}</Panel></div></section>;

  if(module==="clientes") { const rows=filtered(data.clients,["name","document","phone","email"]); return <section className="enterprise-page"><Header title="Clientes" onReload={reload}/>{message&&<p className="enterprise-message">{message}</p>}<div className="enterprise-columns"><form className="enterprise-form" onSubmit={e=>{e.preventDefault();save("client",client,()=>setClient(emptyClient));}}><h3>{editing.type==="client"?"Editar cliente":"Novo cliente"}</h3><input required placeholder="Nome / Razão social" value={client.name} onChange={e=>setClient({...client,name:e.target.value})}/><input placeholder="CPF/CNPJ" value={client.document} onChange={e=>setClient({...client,document:e.target.value})}/><input placeholder="Telefone" value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})}/><input type="email" placeholder="E-mail" value={client.email} onChange={e=>setClient({...client,email:e.target.value})}/><input placeholder="Endereço" value={client.address} onChange={e=>setClient({...client,address:e.target.value})}/><textarea placeholder="Observações" value={client.notes} onChange={e=>setClient({...client,notes:e.target.value})}/><button className="primary-button">{editing.type==="client"?"Atualizar":"Salvar na nuvem"}</button></form><Panel title="Clientes cadastrados" search={search} setSearch={setSearch}>{rows.map(r=><CrudRow key={r.id} title={r.name} subtitle={`${r.document||"Sem documento"} • ${r.phone||"Sem telefone"}`} onEdit={()=>edit("client",r,setClient)} onDelete={()=>remove("lg_clients",r.id)}/>)}</Panel></div></section>; }

  if(module==="imoveis") { const rows=filtered(data.properties,["name","municipality","registration","car_code","sigef_code"]); return <section className="enterprise-page"><Header title="Imóveis" onReload={reload}/>{message&&<p className="enterprise-message">{message}</p>}<div className="enterprise-columns"><form className="enterprise-form" onSubmit={e=>{e.preventDefault();save("property",property,()=>setProperty(emptyProperty));}}><h3>{editing.type==="property"?"Editar imóvel":"Novo imóvel"}</h3><select value={property.client_id||""} onChange={e=>setProperty({...property,client_id:e.target.value||null})}><option value="">Cliente não vinculado</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input required placeholder="Nome do imóvel" value={property.name} onChange={e=>setProperty({...property,name:e.target.value})}/><div className="enterprise-inline"><input placeholder="Município" value={property.municipality} onChange={e=>setProperty({...property,municipality:e.target.value})}/><input maxLength="2" placeholder="UF" value={property.state} onChange={e=>setProperty({...property,state:e.target.value.toUpperCase()})}/></div><input placeholder="Matrícula" value={property.registration} onChange={e=>setProperty({...property,registration:e.target.value})}/><input placeholder="Código CAR/SIMCAR" value={property.car_code} onChange={e=>setProperty({...property,car_code:e.target.value})}/><input placeholder="Código SIGEF" value={property.sigef_code} onChange={e=>setProperty({...property,sigef_code:e.target.value})}/><input placeholder="Área em hectares" value={property.area_ha??""} onChange={e=>setProperty({...property,area_ha:e.target.value})}/><select value={property.status} onChange={e=>setProperty({...property,status:e.target.value})}><option>Em andamento</option><option>Aguardando documentos</option><option>Em análise</option><option>Concluído</option><option>Suspenso</option></select><textarea placeholder="Observações" value={property.notes} onChange={e=>setProperty({...property,notes:e.target.value})}/><button className="primary-button">{editing.type==="property"?"Atualizar":"Salvar na nuvem"}</button></form><Panel title="Imóveis cadastrados" search={search} setSearch={setSearch}>{rows.map(r=><CrudRow key={r.id} title={r.name} subtitle={`${r.municipality||"-"}/${r.state||"-"} • ${r.area_ha?Number(r.area_ha).toLocaleString("pt-BR"):"0"} ha • ${clientName(r.client_id)}`} onEdit={()=>edit("property",r,setProperty)} onDelete={()=>remove("lg_properties",r.id)}/>)}</Panel></div></section>; }

  if(module==="relatorios") { const rows=filtered(data.reports,["title","report_type","status","summary"]); const print=(r)=>printDocument(r.title,`<div class="meta"><b>Tipo:</b> ${safe(r.report_type)}<br><b>Cliente:</b> ${safe(clientName(r.client_id))}<br><b>Imóvel:</b> ${safe(propertyName(r.property_id))}<br><b>Referência:</b> ${safe(dateBR(r.reference_date))}<br><b>Status:</b> ${safe(r.status)}</div><h2>Resumo</h2><p>${safe(r.summary||"Sem resumo cadastrado.")}</p>`,settings); return <section className="enterprise-page"><Header title="Relatórios" onReload={reload}/>{message&&<p className="enterprise-message">{message}</p>}<div className="enterprise-columns"><form className="enterprise-form" onSubmit={e=>{e.preventDefault();save("report",report,()=>setReport(emptyReport));}}><h3>{editing.type==="report"?"Editar relatório":"Registrar relatório"}</h3><input required placeholder="Título" value={report.title} onChange={e=>setReport({...report,title:e.target.value})}/><select value={report.report_type} onChange={e=>setReport({...report,report_type:e.target.value})}><option>Relatório técnico</option><option>Relatório de sobreposição</option><option>Parecer técnico</option><option>Laudo de posse</option><option>Relatório registral</option></select><select value={report.client_id||""} onChange={e=>setReport({...report,client_id:e.target.value||null})}><option value="">Sem cliente</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={report.property_id||""} onChange={e=>setReport({...report,property_id:e.target.value||null})}><option value="">Sem imóvel</option>{data.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="date" value={report.reference_date||""} onChange={e=>setReport({...report,reference_date:e.target.value})}/><select value={report.status} onChange={e=>setReport({...report,status:e.target.value})}><option>Rascunho</option><option>Em revisão</option><option>Finalizado</option><option>Entregue</option></select><textarea required placeholder="Resumo técnico" value={report.summary} onChange={e=>setReport({...report,summary:e.target.value})}/><button className="primary-button">Salvar registro</button></form><Panel title="Arquivo de relatórios" search={search} setSearch={setSearch}>{rows.map(r=><CrudRow key={r.id} title={r.title} subtitle={`${r.report_type} • ${propertyName(r.property_id)} • ${r.status}`} extra={<button onClick={()=>print(r)}>Abrir / PDF</button>} onEdit={()=>edit("report",r,setReport)} onDelete={()=>remove("lg_reports",r.id)}/>)}</Panel></div></section>; }

  if(module==="propostas") { const rows=filtered(data.proposals,["service","status","scope"]); const print=(p)=>printDocument(`Proposta — ${p.service}`,`<div class="meta"><b>Cliente:</b> ${safe(clientName(p.client_id))}<br><b>Imóvel:</b> ${safe(propertyName(p.property_id))}<br><b>Serviço:</b> ${safe(p.service)}<br><b>Valor:</b> ${safe(money(p.amount))}<br><b>Prazo:</b> ${safe(p.deadline||"A definir")}<br><b>Validade:</b> ${safe(dateBR(p.validity_date))}</div><h2>Escopo</h2><p>${safe(p.scope||"Não informado.")}</p><h2>Condições de pagamento</h2><p>${safe(p.payment_terms||"A combinar.")}</p>`,settings); return <section className="enterprise-page"><Header title="Propostas" onReload={reload}/>{message&&<p className="enterprise-message">{message}</p>}<div className="enterprise-columns"><form className="enterprise-form" onSubmit={e=>{e.preventDefault();save("proposal",proposal,()=>setProposal(emptyProposal));}}><h3>{editing.type==="proposal"?"Editar proposta":"Nova proposta"}</h3><select value={proposal.client_id||""} onChange={e=>setProposal({...proposal,client_id:e.target.value||null})}><option value="">Selecione o cliente</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={proposal.property_id||""} onChange={e=>setProposal({...proposal,property_id:e.target.value||null})}><option value="">Selecione o imóvel</option>{data.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input required placeholder="Serviço" value={proposal.service} onChange={e=>setProposal({...proposal,service:e.target.value})}/><input required placeholder="Valor em R$" value={proposal.amount} onChange={e=>setProposal({...proposal,amount:e.target.value})}/><input placeholder="Prazo de execução" value={proposal.deadline} onChange={e=>setProposal({...proposal,deadline:e.target.value})}/><input type="date" value={proposal.validity_date||""} onChange={e=>setProposal({...proposal,validity_date:e.target.value})}/><textarea placeholder="Escopo dos serviços" value={proposal.scope} onChange={e=>setProposal({...proposal,scope:e.target.value})}/><textarea placeholder="Condições de pagamento" value={proposal.payment_terms} onChange={e=>setProposal({...proposal,payment_terms:e.target.value})}/><select value={proposal.status} onChange={e=>setProposal({...proposal,status:e.target.value})}><option>Em elaboração</option><option>Enviada</option><option>Aprovada</option><option>Recusada</option><option>Concluída</option></select><button className="primary-button">Salvar proposta</button></form><Panel title="Propostas cadastradas" search={search} setSearch={setSearch}>{rows.map(p=><CrudRow key={p.id} title={p.service} subtitle={`${clientName(p.client_id)} • ${money(p.amount)} • ${p.status}`} extra={<button onClick={()=>print(p)}>Abrir / PDF</button>} onEdit={()=>edit("proposal",p,setProposal)} onDelete={()=>remove("lg_proposals",p.id)}/>)}</Panel></div></section>; }

  if(module==="config") return <section className="enterprise-page"><Header title="Configurações" onReload={reload}/>{message&&<p className="enterprise-message">{message}</p>}<div className="enterprise-columns"><form className="enterprise-form" onSubmit={async e=>{e.preventDefault();try{await saveSettings(settings);setMessage("Configurações salvas na nuvem.");}catch(err){setMessage(err.message);}}}><h3>Perfil da empresa</h3><input placeholder="Razão social" value={settings.company_name||""} onChange={e=>setSettings({...settings,company_name:e.target.value})}/><input placeholder="Nome da plataforma" value={settings.trade_name||""} onChange={e=>setSettings({...settings,trade_name:e.target.value})}/><input placeholder="Telefone" value={settings.phone||""} onChange={e=>setSettings({...settings,phone:e.target.value})}/><input placeholder="E-mail" value={settings.email||""} onChange={e=>setSettings({...settings,email:e.target.value})}/><input placeholder="Endereço" value={settings.address||""} onChange={e=>setSettings({...settings,address:e.target.value})}/><input placeholder="Responsável técnico" value={settings.technical_responsible||""} onChange={e=>setSettings({...settings,technical_responsible:e.target.value})}/><input placeholder="CPF/CNPJ ou registro" value={settings.document||""} onChange={e=>setSettings({...settings,document:e.target.value})}/><textarea placeholder="Rodapé dos relatórios" value={settings.report_footer||""} onChange={e=>setSettings({...settings,report_footer:e.target.value})}/><button className="primary-button">Salvar na nuvem</button></form><div><Panel title="Backup e publicação"><button className="secondary-action enterprise-full-button" onClick={()=>downloadJson(`longitude_geo_backup_${new Date().toISOString().slice(0,10)}.json`,{exported_at:new Date().toISOString(),settings,data})}>Baixar backup JSON</button><div className="enterprise-checklist"><p>✓ Login Supabase configurado</p><p>✓ Banco PostGIS operacional</p><p>✓ Módulos administrativos na nuvem</p><p>✓ Build Vite preparado para Vercel</p><p>Próximo: executar o SQL V71, validar os módulos e publicar no GitHub/Vercel.</p></div></Panel><Panel title="Sessão atual"><Row title={session.user?.email||"Usuário autenticado"} subtitle={`ID: ${session.user?.id||"-"}`}/></Panel></div></div></section>;

  return null;
}
function Header({title,onReload}){return <div className="enterprise-toolbar"><div><h3>{title}</h3><p>Cadastro e gestão sincronizados na nuvem.</p></div><button className="secondary-action" onClick={onReload}>Atualizar</button></div>}
function Metric({label,value}){return <div className="enterprise-metric"><span>{label}</span><strong>{value}</strong></div>}
function Panel({title,children,search,setSearch}){return <div className="enterprise-panel"><div className="enterprise-panel-head"><h3>{title}</h3>{setSearch&&<input placeholder="Pesquisar..." value={search} onChange={e=>setSearch(e.target.value)}/>}</div><div className="enterprise-list">{children?.length===0?<p className="muted">Nenhum registro.</p>:children}</div></div>}
function Row({title,subtitle}){return <div className="enterprise-row"><div><strong>{title}</strong><span>{subtitle}</span></div></div>}
function CrudRow({title,subtitle,onEdit,onDelete,extra}){return <div className="enterprise-row"><div><strong>{title}</strong><span>{subtitle}</span></div><div className="enterprise-row-actions">{extra}<button onClick={onEdit}>Editar</button><button className="danger-mini" onClick={onDelete}>Excluir</button></div></div>}
